### ISSUE TITLE
Static file upload web interface

### ISSUE THREAD

**Issue by ecatmur** [thameshareandhounds/thameshareandhounds.github.io#9]
We need a way to upload static binary files (images, PDFs etc) that doesn't require a command line or installing a Git client.

I'm looking at using Zapier to pull files from the thameshareandhounds@gmail.com Drive but can't get it to work.

**Comment by captainrobbo** [comment]
Glad to see you are pushing code!  

What content do you have in mind?

For images, Nic has created a Flickr account and we were going to play around with nice ways to link to them, maybe even this afternoon.    

Another possibility is that I could create something on the raceresults.reportlab.com site allowing a file upload, which would execute some git commands when new files appear

For sets of results, I hope ReportLab will be solving this problem for club webmasters everywhere but will explain how later.

**Comment by ecatmur** [comment]
For now it's course maps (under http://thh.run/courses/) - these would be PNG or PDF so not suitable for Flickr. I might also want to upload GPX files for people with Garmins.

**Comment by njg234908** [comment]
If we're planning for core content (md files) to be managed using git then
won't this be ok for binary files as well?

**Comment by captainrobbo** [comment]
Good point.  But there aren't dozens, so why not just add/commit/push?  I'm
happy to do so if you can't access it easily at work...

We're writing a help page for club members needing to update the site, and
i was thinking of saying "email one of the (four/five) club webmasters for
anything you can't do with a click..."

**Comment by ecatmur** [comment]
Well, obviously _I_ have access to Git at work :) - I was deliberately restricting myself to the web interface to see what was possible there.

OK, I'll upload those files via the command line and we can revisit this if we find a need for club members to upload files that aren't photos or results tables.

**Comment by captainrobbo** [comment]
Nic, the problem is that Git doesn't allow upload through the web UI.   I can guess why: in ReportLab's early days, we had an /ftp/uploads directory and one day we found it was becoming a lively channel for distributing Indian porn movies ;-)

**Comment by captainrobbo** [comment]
By the way, Llewellyn is popping up in a few minutes to work on the help pages.  Any stylistic feedback, fire away!

**Comment by njg234908** [comment]
Just what I commented in reply to your email earlier in the week.

**Comment by captainrobbo** [comment]
Will do.  Sadly we need to learn about Sass and rebuild the CSS, as the
"colour wheel" toy we used doesn't offer enough black-and-white options.
Will try to sort the images and excess menu options now
- Andy

**Comment by njg234908** [comment]
For the menu options I would say just keep it simple to:

About - News - Fixtures - Races - Training

Maybe even fewer.

**Comment by njg234908** [comment]
And maybe better with menu items across the top right like this site:

https://developmentseed.org/

**Comment by captainrobbo** [comment]
We could certainly put a few there; I stuck a little menu there (three dots
at top right) for all the "orphaned" pages.  Another option is to have a
footer at the bottom for "lower priority" links.

I find that the style kit we're using works pretty well on mobile, as the
whole left drawer tucks away and pops out.  By the way, it's resizing much
better since 5min ago.

**Comment by njg234908** [comment]
Scaling much better on mobile now - still favour a single across the top
menu with expand button when required though :)

**Comment by captainrobbo** [comment]
I think we can do that in the current framework - but if Pithy lets you do
drop-down menus, by all means go for it
